# Generated by Django 3.1 on 2021-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.CharField(default='SOME STRING', max_length=400),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Samsung_Tv', max_length=130),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.FloatField(default='2345', max_length=102),
        ),
        migrations.AddField(
            model_name='task',
            name='product_id',
            field=models.CharField(default='122', max_length=122),
        ),
    ]
