# Generated by Django 3.1 on 2021-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210906_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.FloatField(default='23453', max_length=102),
        ),
    ]
